# Generated by Django 5.0.3 on 2024-03-28 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('population', models.BigIntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='President',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('population', models.BigIntegerField()),
                ('size', models.BigIntegerField()),
                ('capital_city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_models.city')),
                ('current_president', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_models.president')),
            ],
        ),
        migrations.CreateModel(
            name='PresidentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ages', models.IntegerField()),
                ('bod', models.DateField()),
                ('net_worth', models.CharField(max_length=256)),
                ('president', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_models.president')),
            ],
        ),
    ]
