# Generated by Django 5.0.3 on 2024-03-24 18:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, validators=[django.core.validators.MinLengthValidator(20)])),
                ('description', models.TextField()),
                ('date_released', models.DateField(default=django.utils.timezone.now)),
                ('ratings', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='')),
                ('language', models.CharField(max_length=256, validators=[django.core.validators.MinLengthValidator(5)])),
                ('country', models.CharField(max_length=256, validators=[django.core.validators.MinLengthValidator(5)])),
                ('genre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movie.genre')),
            ],
        ),
    ]
